{% set version = "3.000" %}

package:
  name: font-ttf-inconsolata
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/googlefonts/Inconsolata/releases/download/v{{ version }}/fonts_ttf.zip
  sha256: 626e8ee07501dbb544b50aa59ac2e4b9ec86b810670158a59c7a3cbaf475548a

build:
  number: 0
  noarch: generic

test:
  requires:
    # dummy to have at least one test env requirement
    - bzip2
  commands:
    - test -f ${PREFIX}/fonts/Inconsolata-Regular.ttf  # [unix]
    - test -f ${PREFIX}/fonts/Inconsolata-Bold.ttf     # [unix]

about:
  home: https://fonts.google.com/specimen/Inconsolata
  summary: Monospace font for pretty code listings
  license: OFL-1.1
  license_file: ofl/inconsolata/OFL.txt
  license_family: Other

extra:
  recipe-maintainers:
    - dbast
