travis:
  secure:
    BINSTAR_TOKEN: BmrbpBbe/rIfAvFBdJmZeUo5yHpU02UzLpBkzOV2yDcJmV5dAqk5gLDpTZVe/3OYfTq6UMIPaFIWTALCi0ocjzoLK5UzoFIiE0CJNZYBgTjS1n2BxzTz3t0LV5wNCrZPgWmezZ93QhNUgJXOevSFwwVH6YqHMK2Kp1W/gQEoyOSFuH0CzaQzFmTP+w1y34tdki3kBizATJBYucQj93jMivwL5uWQie3uUQtAxhcnA3RclVvVFbiftF7/XDP6NJbcZmpWosNLSGJ5HtJ4o8V5KgDLK1uVRPXZ01fOh4QuvXzpL2yz9vXMgCvwngw0gMHlWxC7+EOjpLelGaf+3VsXKrCLHJLs2ThkuagoOYmNjeXHAV1bmOun3eIYFBO22dbVVkUIEHq9FYEtWNUJVUznd9b8kc+jumbglNCENUjmTTqM2dVBvHNlwh5COB6DgowBexsKoVvG2lBZLTXDSB+JDFTs6Yh8v3BbaYZHECsZ1W6Q/emkSmUVoqpAUJlMbNVPDMG4BCJvwSo6Re28RRKVP841Zlpb/OW+EnqiJ+7le81tuSEo4NToqBLaSG4saJiAhIptz1JMhnqPLRNknyckDlawJLebkyjdfgOFMZbrCfHsYEcKvO4U4JZjqSzY1mdTyrf64nqdJuLFyb5GWaXTNHKv9NQdkhe4Te9x756m8Qc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
